version: "3"
services:
  woocommerce:
    # build: ./
    image: bliskapaczkapl/woocommerce
    depends_on:
      - db
    ports:
      - "8080:80"
    env_file:
     - ./env
    environment:
      DB_HOST: db
  db:
    image: mysql
    ports:
      - "3306:3306"
    env_file:
     - ./env